### ISSUE TITLE
Document need to be updated to use what type of subscription

### ISSUE THREAD

**Issue by alberttwong** [gonoph/satellite-install#2]
I attached "Red Hat Satellite Employee Subscription" to my Satellite installation.

**Comment by alberttwong** [comment]
Also you need to copy the UUID for the next step.

**Comment by gonoph** [comment]
I'm unable to describe which Satellite subscription to attach to the server / activation key, as different customers may see different Subscription names. For example, only a Red Hat employee will see the employee subscription, while a customer with an eval will see a 30, 60 or 90 day eval for Satellite. A customer using the transition SKU will see a transition SKU description.

The exercise is left to the consumer to decide which "Satellite Subscription" to best attach to the system profile / activation key.

**Comment by gonoph** [comment]
Added better description in README and bootstrap script to mention copying the UUID.
