### ISSUE TITLE
Set hostname before running 0-bootstrap.sh?

### ISSUE THREAD

**Issue by alberttwong** [gonoph/satellite-install#4]
I don't understand this instruction

```
As a bonus, if you set the hostname beforehand, the script will automatically set the correct IP address for you. This assumes you are using static IPs. If you are using DHCP, then after the ip address is set, the gateway and DNS will be blank.
```

After running 0-bootstrap.sh, my server is still named localhost.localdomain with IP 127.0.0.1

**Comment by alberttwong** [comment]
I tried to manually set it after the fact and dthen re-run 'make install'.   I got another error.  It looks like I need to do a clean install.

**Comment by gonoph** [comment]
Updated the README.md, added an sanity check, and updated the validation message to better describe what's being expected of the hostname.
