### ISSUE TITLE
Got error running "make install"....  fully qualified hostname

### ISSUE THREAD

**Issue by alberttwong** [gonoph/satellite-install#5]
Seems like there is a error in the `make install`.  Says it needs a fully qualified hostname in /etc/hosts.   Seems to be related to https://github.com/gonoph/satellite-install/issues/4.    Need a check before running the script.

**Comment by gonoph** [comment]
Satellite requires your hostname to a FQDN of the IP address of the server. Updated the documentation to reflect this.
